// Generated by tools/generate_nose_mask.py from the original basalt nose.
// Artwork-relative coordinates; the caller supplies the cat's horizontal shift.
#pragma once
#include <pebble.h>

#if defined(PBL_BW)
static void draw_gray_nose(GContext *ctx, int shift) {
  static const uint16_t rows[16] = {0x1fc0,0x1ff0,0x1ff0,0xffff,0xffff,0xffff,0xffff,0xffff,0xffff,0x03f0,0x03f0,0x03f0,0x0300,0x0300,0x0700,0x0700};
  static const uint8_t bayer[4][4] = {{0,8,2,10},{12,4,14,6},{3,11,1,9},{15,7,13,5}};
  for (int row = 0; row < 16; ++row) {
    for (int column = 0; column < 16; ++column) {
      if (!(rows[row] & (1u << column))) continue;
      int x = 55 + shift + column;
      int y = 110 + row;
      graphics_context_set_fill_color(ctx, bayer[y & 3][x & 3] < 5 ? GColorWhite : GColorBlack);
      graphics_fill_rect(ctx, GRect(x, y, 1, 1), 0, GCornerNone);
    }
  }
}
#else
static inline void draw_gray_nose(GContext *ctx, int shift) {
  (void)ctx;
  (void)shift;
}
#endif
