"""Generate small drawing spans that preserve the original eyes on a white cat.
No source artwork is modified. Eye outlines separate pale eyes from white fur.
"""
from pathlib import Path
from collections import deque
from PIL import Image
root=Path(__file__).resolve().parents[1]
out=['// Generated by tools/generate_disconnect_eyes.py. Original eye shapes and pupils.','#pragma once','#include <pebble.h>','static void draw_disconnect_eyes(GContext *ctx, int shift) {','typedef struct { uint8_t x,y,w,color; } EyeSpan;']
for index,platform in enumerate(['aplite','basalt','chalk','diorite','emery','flint','gabbro']):
    src=root/'resources/images'/('loadingcat_bg.png' if platform=='emery' else f'loadingcat_bg~{platform}.png')
    im=Image.open(src).convert('RGB');w,h=im.size
    points={(x,y) for y in range(h) for x in range(w) if min(im.getpixel((x,y)))>150}
    components=[]
    while points:
        start=points.pop();component={start};queue=deque([start])
        while queue:
            x,y=queue.popleft()
            for p in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
                if p in points:points.remove(p);component.add(p);queue.append(p)
        cx=sum(p[0] for p in component)/len(component);cy=sum(p[1] for p in component)/len(component)
        if len(component)>25 and .15*w<cx<.8*w and .45*h<cy<.70*h:components.append(component)
    assert len(components)==2,(platform,[(len(c),min(c),max(c)) for c in components])
    pixels={}
    for component in components:
        filled=set()
        for y in {p[1] for p in component}:
            xs=[x for x,yy in component if yy==y]
            filled.update((x,y) for x in range(min(xs),max(xs)+1))
        for x,y in filled:
            for dx,dy in [(0,0),(-1,0),(1,0),(0,-1),(0,1)]:pixels[x+dx,y+dy]=0xc0
        for x,y in filled:
            r,g,b=im.getpixel((x,y))
            if platform in ['aplite','diorite','flint']:color=0xff if min((r,g,b))>150 else 0xc0
            else:color=0xc0|((r+42)//85<<4)|((g+42)//85<<2)|((b+42)//85)
            pixels[x,y]=color
    spans=[]
    for y in sorted({p[1] for p in pixels}):
        xs=sorted(x for x,yy in pixels if yy==y);start=previous=xs[0];color=pixels[start,y]
        for x in xs[1:]:
            if x!=previous+1 or pixels[x,y]!=color:spans.append((start,y,previous-start+1,color));start=x;color=pixels[x,y]
            previous=x
        spans.append((start,y,previous-start+1,color))
    out.append(('#if' if index==0 else '#elif')+f' defined(PBL_PLATFORM_{platform.upper()})')
    out.append('static const EyeSpan spans[] = {'+','.join('{%d,%d,%d,0x%02x}'%s for s in spans)+'};')
    print(platform,len(spans),'eye spans')
out.extend(['#endif','for (unsigned i=0;i<sizeof(spans)/sizeof(spans[0]);++i) {','GColor color = {.argb=spans[i].color};','graphics_context_set_fill_color(ctx,color);','graphics_fill_rect(ctx,GRect(spans[i].x+shift,spans[i].y,spans[i].w,1),0,GCornerNone);','}','}'])
(root/'src/c/disconnect_eyes.h').write_text('\n'.join(out)+'\n')
