"""Extract only the color cat's nose for an optional monochrome overlay.

The original bitmap assets are never changed. Run with Pillow installed.
"""
from pathlib import Path
from collections import deque
import argparse
import hashlib
import json
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--study-dir', type=Path, help='Optional directory for before/after images and verification')
parser.add_argument('--capture-dir', type=Path, help='Existing native screenshots, required with --study-dir')
args = parser.parse_args()
if args.study_dir and not args.capture_dir:
    parser.error('--study-dir also requires --capture-dir')
OUT = args.study_dir
IMAGES = REPO / 'resources/images'
SOURCE = IMAGES / 'loadingcat_bg~basalt.png'
ROI = (54, 109, 72, 127)  # Nose only; excludes eyes, cheek marks and whiskers.
BAYER = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))
COVERAGE = 5
SHIFT = 7
original_hashes = {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                   for p in IMAGES.glob('*.png')}
source = Image.open(SOURCE).convert('RGB')
assert source.size == (144, 168)
pixels = set()
for y in range(ROI[1], ROI[3]):
    for x in range(ROI[0], ROI[2]):
        rgb = source.getpixel((x, y))
        # The native palette makes these pixels dark gray; near-black edge
        # samples remain black. The bounded region contains no other feature.
        if 43 <= sum(rgb) // 3 <= 128 and max(rgb) - min(rgb) <= 16:
            pixels.add((x, y))
assert len(pixels) == 149, 'Original nose silhouette changed; inspect before regenerating'
remaining = set(pixels)
queue = deque([remaining.pop()])
while queue:
    x, y = queue.popleft()
    for point in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
        if point in remaining:
            remaining.remove(point)
            queue.append(point)
assert not remaining, 'The nose must be one connected silhouette'
left = min(x for x, _ in pixels)
top = min(y for _, y in pixels)
width = max(x for x, _ in pixels) - left + 1
height = max(y for _, y in pixels) - top + 1
rows = [''.join('1' if (x, y) in pixels else '0' for x in range(left, left + width))
        for y in range(top, top + height)]
assert (left, top, width, height) == (55, 110, 16, 16)
mask = {'x': left, 'y': top, 'width': width, 'height': height,
        'rows': rows, 'coverage': COVERAGE, 'bayer': BAYER, 'anchor': 'screen'}
(REPO / 'src/pkjs/nose-mask.json').write_text(json.dumps(mask, separators=(',', ':')) + '\n')

row_masks = [sum(1 << x for x, value in enumerate(row) if value == '1') for row in rows]
header = '''// Generated by tools/generate_nose_mask.py from the original basalt nose.
// Artwork-relative coordinates; the caller supplies the cat's horizontal shift.
#pragma once
#include <pebble.h>

#if defined(PBL_BW)
static void draw_gray_nose(GContext *ctx, int shift) {
  static const uint16_t rows[16] = {%s};
  static const uint8_t bayer[4][4] = {{0,8,2,10},{12,4,14,6},{3,11,1,9},{15,7,13,5}};
  for (int row = 0; row < 16; ++row) {
    for (int column = 0; column < 16; ++column) {
      if (!(rows[row] & (1u << column))) continue;
      int x = 55 + shift + column;
      int y = 110 + row;
      graphics_context_set_fill_color(ctx, bayer[y & 3][x & 3] < 5 ? GColorWhite : GColorBlack);
      graphics_fill_rect(ctx, GRect(x, y, 1, 1), 0, GCornerNone);
    }
  }
}
#else
static inline void draw_gray_nose(GContext *ctx, int shift) {
  (void)ctx;
  (void)shift;
}
#endif
''' % ','.join(f'0x{row:04x}' for row in row_masks)
(REPO / 'src/c/nose.h').write_text(header)

for platform in ('aplite', 'diorite', 'flint'):
    bitmap = Image.open(IMAGES / f'loadingcat_bg~{platform}.png').convert('RGB')
    assert bitmap.size == source.size
    if platform != 'flint':
        assert all(bitmap.getpixel(point) == (0, 0, 0) for point in pixels)
    else:
        assert all(bitmap.getpixel(point) == source.getpixel(point) for point in pixels)
assert original_hashes == {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                            for p in IMAGES.glob('*.png')}
if OUT is None:
    print('Generated 16x16 nose mask at (55,110), 149 silhouette pixels; original artwork unchanged.')
    raise SystemExit(0)
OUT.mkdir(parents=True, exist_ok=True)
checks = []
font = ImageFont.truetype(str(REPO / 'resources/fonts/Baloo2-ExtraBold.ttf'), 22)
small = ImageFont.truetype(str(REPO / 'resources/fonts/Baloo2-ExtraBold.ttf'), 18)
sheet = Image.new('RGB', (1008, 826), '#f3eee4')
draw = ImageDraw.Draw(sheet)
for index, (platform, label) in enumerate((('aplite', 'Pebble / Steel'), ('diorite', 'Pebble 2'), ('flint', '2 Duo'))):
    native = Image.open(args.capture_dir / f'{platform}-slow.png').convert('RGB')
    before = native.copy()
    # The selected face may already have the option enabled. Restore only the
    # known monochrome nose silhouette to its original black for the off view.
    for x, y in pixels:
        before.putpixel((x + SHIFT, y), (0, 0, 0))
    after = before.copy()
    for x, y in pixels:
        screen_x = x + SHIFT
        ink = 255 if BAYER[y % 4][screen_x % 4] < COVERAGE else 0
        after.putpixel((screen_x, y), (ink, ink, ink))
    changed = {(x, y) for y in range(after.height) for x in range(after.width)
               if before.getpixel((x, y)) != after.getpixel((x, y))}
    assert changed <= {(x + SHIFT, y) for x, y in pixels}
    assert changed
    before.save(OUT / f'{platform}-nose-off.png')
    after.save(OUT / f'{platform}-nose-on.png')
    checks.append({'platform': platform, 'mask_pixels': len(pixels), 'changed_pixels': len(changed),
                   'all_changes_inside_nose': True, 'source_geometry_aligned': True})
    x = index * 336 + 24
    draw.text((x, 10), label, font=font, fill='#292821')
    draw.text((x, 43), 'Nose off', font=small, fill='#656159')
    sheet.paste(before.resize((288, 336), Image.Resampling.NEAREST), (x, 75))
    draw.text((x, 440), 'Gray nose on', font=small, fill='#656159')
    sheet.paste(after.resize((288, 336), Image.Resampling.NEAREST), (x, 472))
sheet.save(OUT / 'comparison.png')
assert original_hashes == {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                            for p in IMAGES.glob('*.png')}
(OUT / 'verification.json').write_text(json.dumps({'source': str(SOURCE.relative_to(REPO)),
    'source_sha256': original_hashes[SOURCE.name], 'source_roi': ROI, 'mask': mask,
    'checks': checks, 'original_bitmaps_unchanged': True}, indent=2) + '\n')
print('Generated 16x16 nose mask at (55,110), 149 silhouette pixels; all three BW placements verified.')
