#!/usr/bin/env python3
"""Derive compact temperature ink bounds from the shipped development rasters.

No font outlines are changed. generate_tall_font.py invokes this after refreshing
the rasters. Run with --check to detect stale generated metrics.
"""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
fonts = json.loads((root / 'tools/development/preview-assets.json').read_text())['fonts']
families = (0, 2, 7, 8)
sizes = (22, 18, 16)
characters = '0123456789-°'
metrics = []
for family in families:
    family_metrics = []
    for size in sizes:
        glyphs = fonts[f'n{family}-{size}']['glyphs']
        size_metrics = []
        for character in characters:
            glyph = glyphs[character]
            pixels = [(glyph['x'] + x, glyph['y'] + y)
                      for y, row in enumerate(glyph['rows'])
                      for x, value in enumerate(row) if value == '1']
            assert pixels, (family, size, character)
            xs, ys = zip(*pixels)
            bounds = [glyph['advance'], min(xs), max(xs), min(ys), max(ys)]
            assert all(-128 <= value <= 127 for value in bounds)
            size_metrics.append(bounds)
        family_metrics.append(size_metrics)
    metrics.append(family_metrics)

header = '''#pragma once
#include <stdint.h>
// Generated by tools/generate_temperature_metrics.py from actual glyph ink.
// Families: Teko, Bebas Neue, Square, Square Cut. Sizes: 22, 18, 16.
// Glyphs: 0-9, minus, degree. Bounds are inclusive and relative to the glyph pen.
typedef struct {
  int8_t advance, left, right, top, bottom;
} TemperatureGlyph;
static const TemperatureGlyph TEMPERATURE_GLYPHS[4][3][12] = '''
header += json.dumps(metrics, separators=(',', ':')).replace('[', '{').replace(']', '}') + ';\n'
header += '''static inline const TemperatureGlyph *temperature_glyphs(int family, int size) {
  int family_index = family == 0 ? 0 : (family == 7 ? 2 : (family == 8 ? 3 : 1));
  return TEMPERATURE_GLYPHS[family_index][size == 22 ? 0 : (size == 18 ? 1 : 2)];
}
'''
target = root / 'src/c/temperature_metrics.h'
if args.check:
    assert target.read_text() == header, 'Regenerate temperature metrics after updating font rasters'
    print('Temperature metrics match all 144 shipped glyph rasters.')
else:
    target.write_text(header)
    print('Generated temperature metrics for four fonts at three sizes (720 bytes).')
